# Generated by Django 4.1.5 on 2023-02-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time_log',
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
